import { notFound } from "next/navigation";
import Image from "next/image";
import { prisma } from "@/server/db";
import { requirePageUser } from "@/server/auth/require-user";
import { imageAction, uploadPublicImages } from "@/server/actions/public-programming";
import { Card, Field, buttonClass, inputClass } from "@/components/ui";
import { ExperienceForm } from "../experience-form";
export const dynamic="force-dynamic";
export default async function EditPage({params}:{params:Promise<{id:string}>}) { await requirePageUser("ADMIN"); const {id}=await params; const item=await prisma.publicExperience.findUnique({where:{id},include:{schedules:{orderBy:{position:"asc"}},images:{select:{id:true,alt:true,isCover:true,position:true},orderBy:{position:"asc"}}}}); if(!item)notFound(); return <div className="space-y-4"><ExperienceForm item={item}/><Card className="space-y-4"><h2 className="font-serif text-xl">Imágenes</h2><p className="text-sm text-tinta-suave">La primera imagen se usa como portada. Formatos JPG, PNG o WebP, hasta 5 MB cada una.</p><form action={uploadPublicImages} className="space-y-3"><input type="hidden" name="experienceId" value={id}/><Field label="Agregar fotos"><input className={inputClass()} type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple required/></Field><Field label="Texto alternativo"><input className={inputClass()} name="alt" maxLength={180} placeholder={item.title}/></Field><button className={buttonClass("primary")}>Subir imágenes</button></form><div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3">{item.images.map(img=><div key={img.id} className="overflow-hidden rounded-lg border border-borde"><Image src={`/api/programacion/imagenes/${img.id}`} alt={img.alt??item.title} width={500} height={320} className="h-40 w-full object-cover" unoptimized/><form action={imageAction} className="flex gap-2 p-2"><input type="hidden" name="imageId" value={img.id}/>{!img.isCover&&<button name="intent" value="cover" className={buttonClass("secondary","min-h-9 px-2 py-1 text-xs")}>Usar de portada</button>}<button name="intent" value="delete" className={buttonClass("danger","min-h-9 px-2 py-1 text-xs")}>Eliminar</button></form>{img.isCover&&<p className="px-2 pb-2 text-xs text-exito">Portada</p>}</div>)}</div></Card></div>; }
